

# 例子
examples:
  - name         : Component of VUE togethe
    repository   : github:kenote/vue-component-example
    value        : vue-component-example
    results      :
      - name       : To get started
        content    :
          - npm run serve
      - name       : To generate lib
        content    :
          - npm run lib
      - name       : To build
        content    :
          - npm run build
  - name         : Nuxt.js static website.
    repository   : github:kenote/nuxt-static-example
    value        : nuxt-static-example
    results      :
      - name       : To get started
        content    :
          - npm run dev
      - name       : To generate html
        content    :
          - npm run generate
  - name         : Next.js static website.
    repository   : github:kenote/next-static-example
    value        : next-static-example
    results      :
      - name       : To get started
        content    :
          - npm run dev
      - name       : To export html
        content    :
          - npm run export
  - name         : Nuxt.js with Express.
    repository   : github:kenote/nuxt-express-example
    value        : nuxt-express-example
    results      :
      - name       : To get started
        content    :
          - npm run develop
      - name       : To get build
        content    :
          - npm run build
  - name         : Next.js with Express.
    repository   : github:kenote/next-express-example
    value        : next-express-example
    results      :
      - name       : To get started
        content    :
          - npm run develop
      - name       : To get build
        content    :
          - npm run build